apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jppt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0051-tenant/tkrw-pr712-0075-0051-app/devfile-sample-jppt@sha256:044d8752ddc21cac8c03b4baa75d863fe27ab5aac234a7052d55c3cbf2155334
        name: my-nodejs
        resources: {}
status: {}
